### ISSUE TITLE
Feather roadmap

### ISSUE THREAD

**Issue by frankdou** [Wiredcraft/feathers#24]
![Monit](https://github.com/Wiredcraft/feathers/raw/master/extra/feather.png)
# Todo
- [x] Switching current code to jekyll branch
- [x] Folder structure
- [x] Angular structure
- [x] html boilerplate with a reset.css and list of all main html elements
- [ ] customizing the html page with SCSS/compass
- [ ] Grunt with SCSS/compass compilation and static server
- [ ] [satan](https://github.com/wandoulabs/satan)
- [ ] [generator-angular](https://github.com/frankdou/generator-angular)
- [ ] [totoro](https://github.com/totorojs/totoro)
- [ ] Transforming Feathers into a grunt-init template
# Background

After done the other works, we will creating related stuff.

After using angular , we think its not good to make a boilerplate to record best practices.

So we will make a basic boilerplate for starting the project, and a wiki record the related experience.

We will see, pick code and get idea from these repo:
-  wandoulab's [satan](https://github.com/wandoulabs/satan)
-  yeoman's[generator-angular](https://github.com/frankdou/generator-angular)  
-  alex's [grunt-init-template](https://github.com/unitech/grunt-init-template)  code to improve efficiency and quality.
- alipay's [totoro](https://github.com/totorojs/totoro)

We may bring in something like this:
1.  Yeoman  (for init template, create files, not sure, doesnt see much)
2.  Grunt (for the static server, convet scss to css, files merging and so on)
3.  bower (for quick download and update the related js library)
4.  karma (for convenient front-end test)
5.  compas and foundation (for quick css)
